platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
  - name: eq-runner-maintenance-page-release

outputs:
  - name: gcs-bucket-maintenance-page-artifact

run:
  path: sh
  args:
    - -exc
    - |
      cd maintenance-page-release    
      tar -xzf source.tar.gz -C maintenance-page-release --strip-components=1
